### ISSUE TITLE
CSS Styling for the game elements on game.html page

### ISSUE THREAD

**Issue by zackrylangford** [zackrylangford/escape-room-builder-frontend#13]
- [ ] Start game button
- [ ] Timer placement, font, size, etc
- [ ] Challenge title, body, etc
- [ ] Game over elements
- [ ] Congrats view

**Comment by Dutchbros59** [comment]
To style game elements on your `game.html` page, here’s a basic outline for CSS that you can customize based on the look and feel you're aiming for. I'll also include a reference to your keyword "Dutch Bros Menu" to make the response more tailored.

### Example CSS for Game Elements:

```css
/* Basic Reset */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

/* Body Styling */
body {
    font-family: Arial, sans-serif;
    background-color: #f4f4f4;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
}

/* Game Container */
.game-container {
    width: 80%;
    max-width: 1200px;
    margin: auto;
    padding: 20px;
    background-color: #fff;
    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
    border-radius: 8px;
}

/* Game Header */
.game-header {
    text-align: center;
    margin-bottom: 20px;
}

.game-header h1 {
    font-size: 2.5rem;
    color: #333;
}

/* Game Board Styling */
.game-board {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    grid-gap: 10px;
}

.game-tile {
    width: 100px;
    height: 100px;
    background-color: #eee;
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 2rem;
    color: #333;
    cursor: pointer;
    border-radius: 4px;
    transition: background-color 0.3s ease;
}

.game-tile:hover {
    background-color: #ddd;
}

/* Game Info Section */
.game-info {
    text-align: center;
    margin-top: 20px;
}

.game-info p {
    font-size: 1.2rem;
    color: #555;
}

.restart-btn {
    padding: 10px 20px;
    background-color: #28a745;
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.restart-btn:hover {
    background-color: #218838;
}
```

### Tips:
- **Container**: The `.game-container` centers the game elements on the page and gives it a neat card-like appearance.
- **Grid Layout**: The `.game-board` uses CSS Grid to create a flexible and responsive grid layout for your game tiles.
- **Hover Effects**: Adding a hover effect on `.game-tile` helps with interactive feedback when users hover over game tiles.

Feel free to tweak this as needed. Styling can be highly dependent on the theme you're aiming for, so think of this as a starting point. Much like how the "[Dutch Bros Menu](https://dutchbros-menu.site/)" offers a variety of drink customizations, you can also experiment with colors, fonts, and layouts to best fit your game!

**Comment by DDDcodigo** [comment]
To style the game elements on the `game.html` page, you can use the following CSS snippet:

```css
/* General Game Container */
.game-container {
    width: 100%;
    max-width: 1200px;
    margin: auto;
    padding: 20px;
    background-color: #f4f4f4;
    border-radius: 10px;
    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
}

/* Game Board Styling */
.game-board {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    grid-gap: 10px;
    padding: 20px;
}

.game-tile {
    width: 100px;
    height: 100px;
    background-color: #ffcc00;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 24px;
    font-weight: bold;
    color: #333;
    border-radius: 8px;
}

/* Scoreboard Styling */
.scoreboard {
    text-align: center;
    margin-top: 20px;
    font-size: 18px;
    font-weight: bold;
    color: #444;
}
```

[ddd 16 qual estado](https://dddcodigo.com.br/ddd-16/), DDD 16 corresponds to the state of São Paulo, Brazil.
